/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardMRouteImport } from './routes/dashboard/m'
import { Route as DashboardSuperAdminRouteImport } from './routes/dashboard/super-admin'
import { Route as ApiPublicAuthCheckRouteImport } from './routes/api/public/auth-check'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin.index'
import { Route as DashboardAdminAccountRouteImport } from './routes/dashboard/admin.account'
import { Route as DashboardAdminAttendanceRouteImport } from './routes/dashboard/admin.attendance'
import { Route as DashboardAdminMembersRouteImport } from './routes/dashboard/admin.members'
import { Route as DashboardAdminPaymentsRouteImport } from './routes/dashboard/admin.payments'
import { Route as DashboardAdminPlansRouteImport } from './routes/dashboard/admin.plans'
import { Route as DashboardAdminQrManagementRouteImport } from './routes/dashboard/admin.qr-management'
import { Route as DashboardMIndexRouteImport } from './routes/dashboard/m.index'
import { Route as DashboardMAttendanceRouteImport } from './routes/dashboard/m.attendance'
import { Route as DashboardMPaymentsRouteImport } from './routes/dashboard/m.payments'
import { Route as DashboardMPlansRouteImport } from './routes/dashboard/m.plans'
import { Route as DashboardMProfileRouteImport } from './routes/dashboard/m.profile'
import { Route as DashboardSuperAdminIndexRouteImport } from './routes/dashboard/super-admin.index'
import { Route as DashboardSuperAdminGymsRouteImport } from './routes/dashboard/super-admin.gyms'
import { Route as DashboardSuperAdminPaymentsRouteImport } from './routes/dashboard/super-admin.payments'
import { Route as DashboardSuperAdminPlansRouteImport } from './routes/dashboard/super-admin.plans'
import { Route as DashboardAdminPlansNewRouteImport } from './routes/dashboard/admin.plans.new'
import { Route as DashboardAdminSettingsIndexRouteImport } from './routes/dashboard/admin.settings/index'
import { Route as DashboardSuperAdminGymsIndexRouteImport } from './routes/dashboard/super-admin.gyms.index'
import { Route as DashboardSuperAdminGymsGymIdRouteImport } from './routes/dashboard/super-admin.gyms.$gymId'
import { Route as DashboardSuperAdminGymsAddRouteImport } from './routes/dashboard/super-admin.gyms.add'
import { Route as DashboardAdminPlansEditPlanIdRouteImport } from './routes/dashboard/admin.plans.edit.$planId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMRoute = DashboardMRouteImport.update({
  id: '/m',
  path: '/m',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSuperAdminRoute = DashboardSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicAuthCheckRoute = ApiPublicAuthCheckRouteImport.update({
  id: '/api/public/auth-check',
  path: '/api/public/auth-check',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminAccountRoute = DashboardAdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminAttendanceRoute =
  DashboardAdminAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminMembersRoute = DashboardAdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminPaymentsRoute = DashboardAdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminPlansRoute = DashboardAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminQrManagementRoute =
  DashboardAdminQrManagementRouteImport.update({
    id: '/qr-management',
    path: '/qr-management',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardMIndexRoute = DashboardMIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardMRoute,
} as any)
const DashboardMAttendanceRoute = DashboardMAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => DashboardMRoute,
} as any)
const DashboardMPaymentsRoute = DashboardMPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardMRoute,
} as any)
const DashboardMPlansRoute = DashboardMPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => DashboardMRoute,
} as any)
const DashboardMProfileRoute = DashboardMProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardMRoute,
} as any)
const DashboardSuperAdminIndexRoute =
  DashboardSuperAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardSuperAdminRoute,
  } as any)
const DashboardSuperAdminGymsRoute = DashboardSuperAdminGymsRouteImport.update({
  id: '/gyms',
  path: '/gyms',
  getParentRoute: () => DashboardSuperAdminRoute,
} as any)
const DashboardSuperAdminPaymentsRoute =
  DashboardSuperAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => DashboardSuperAdminRoute,
  } as any)
const DashboardSuperAdminPlansRoute =
  DashboardSuperAdminPlansRouteImport.update({
    id: '/plans',
    path: '/plans',
    getParentRoute: () => DashboardSuperAdminRoute,
  } as any)
const DashboardAdminPlansNewRoute = DashboardAdminPlansNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardAdminPlansRoute,
} as any)
const DashboardAdminSettingsIndexRoute =
  DashboardAdminSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardSuperAdminGymsIndexRoute =
  DashboardSuperAdminGymsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardSuperAdminGymsRoute,
  } as any)
const DashboardSuperAdminGymsGymIdRoute =
  DashboardSuperAdminGymsGymIdRouteImport.update({
    id: '/$gymId',
    path: '/$gymId',
    getParentRoute: () => DashboardSuperAdminGymsRoute,
  } as any)
const DashboardSuperAdminGymsAddRoute =
  DashboardSuperAdminGymsAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => DashboardSuperAdminGymsRoute,
  } as any)
const DashboardAdminPlansEditPlanIdRoute =
  DashboardAdminPlansEditPlanIdRouteImport.update({
    id: '/edit/$planId',
    path: '/edit/$planId',
    getParentRoute: () => DashboardAdminPlansRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/m': typeof DashboardMRouteWithChildren
  '/dashboard/super-admin': typeof DashboardSuperAdminRouteWithChildren
  '/api/public/auth-check': typeof ApiPublicAuthCheckRoute
  '/dashboard/admin/account': typeof DashboardAdminAccountRoute
  '/dashboard/admin/attendance': typeof DashboardAdminAttendanceRoute
  '/dashboard/admin/members': typeof DashboardAdminMembersRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/admin/plans': typeof DashboardAdminPlansRouteWithChildren
  '/dashboard/admin/qr-management': typeof DashboardAdminQrManagementRoute
  '/dashboard/m/attendance': typeof DashboardMAttendanceRoute
  '/dashboard/m/payments': typeof DashboardMPaymentsRoute
  '/dashboard/m/plans': typeof DashboardMPlansRoute
  '/dashboard/m/profile': typeof DashboardMProfileRoute
  '/dashboard/super-admin/gyms': typeof DashboardSuperAdminGymsRouteWithChildren
  '/dashboard/super-admin/payments': typeof DashboardSuperAdminPaymentsRoute
  '/dashboard/super-admin/plans': typeof DashboardSuperAdminPlansRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/m/': typeof DashboardMIndexRoute
  '/dashboard/super-admin/': typeof DashboardSuperAdminIndexRoute
  '/dashboard/admin/plans/new': typeof DashboardAdminPlansNewRoute
  '/dashboard/super-admin/gyms/$gymId': typeof DashboardSuperAdminGymsGymIdRoute
  '/dashboard/super-admin/gyms/add': typeof DashboardSuperAdminGymsAddRoute
  '/dashboard/admin/settings/': typeof DashboardAdminSettingsIndexRoute
  '/dashboard/super-admin/gyms/': typeof DashboardSuperAdminGymsIndexRoute
  '/dashboard/admin/plans/edit/$planId': typeof DashboardAdminPlansEditPlanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/api/public/auth-check': typeof ApiPublicAuthCheckRoute
  '/dashboard/admin/account': typeof DashboardAdminAccountRoute
  '/dashboard/admin/attendance': typeof DashboardAdminAttendanceRoute
  '/dashboard/admin/members': typeof DashboardAdminMembersRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/admin/plans': typeof DashboardAdminPlansRouteWithChildren
  '/dashboard/admin/qr-management': typeof DashboardAdminQrManagementRoute
  '/dashboard/m/attendance': typeof DashboardMAttendanceRoute
  '/dashboard/m/payments': typeof DashboardMPaymentsRoute
  '/dashboard/m/plans': typeof DashboardMPlansRoute
  '/dashboard/m/profile': typeof DashboardMProfileRoute
  '/dashboard/super-admin/payments': typeof DashboardSuperAdminPaymentsRoute
  '/dashboard/super-admin/plans': typeof DashboardSuperAdminPlansRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/m': typeof DashboardMIndexRoute
  '/dashboard/super-admin': typeof DashboardSuperAdminIndexRoute
  '/dashboard/admin/plans/new': typeof DashboardAdminPlansNewRoute
  '/dashboard/super-admin/gyms/$gymId': typeof DashboardSuperAdminGymsGymIdRoute
  '/dashboard/super-admin/gyms/add': typeof DashboardSuperAdminGymsAddRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsIndexRoute
  '/dashboard/super-admin/gyms': typeof DashboardSuperAdminGymsIndexRoute
  '/dashboard/admin/plans/edit/$planId': typeof DashboardAdminPlansEditPlanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/m': typeof DashboardMRouteWithChildren
  '/dashboard/super-admin': typeof DashboardSuperAdminRouteWithChildren
  '/api/public/auth-check': typeof ApiPublicAuthCheckRoute
  '/dashboard/admin/account': typeof DashboardAdminAccountRoute
  '/dashboard/admin/attendance': typeof DashboardAdminAttendanceRoute
  '/dashboard/admin/members': typeof DashboardAdminMembersRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/admin/plans': typeof DashboardAdminPlansRouteWithChildren
  '/dashboard/admin/qr-management': typeof DashboardAdminQrManagementRoute
  '/dashboard/m/attendance': typeof DashboardMAttendanceRoute
  '/dashboard/m/payments': typeof DashboardMPaymentsRoute
  '/dashboard/m/plans': typeof DashboardMPlansRoute
  '/dashboard/m/profile': typeof DashboardMProfileRoute
  '/dashboard/super-admin/gyms': typeof DashboardSuperAdminGymsRouteWithChildren
  '/dashboard/super-admin/payments': typeof DashboardSuperAdminPaymentsRoute
  '/dashboard/super-admin/plans': typeof DashboardSuperAdminPlansRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/m/': typeof DashboardMIndexRoute
  '/dashboard/super-admin/': typeof DashboardSuperAdminIndexRoute
  '/dashboard/admin/plans/new': typeof DashboardAdminPlansNewRoute
  '/dashboard/super-admin/gyms/$gymId': typeof DashboardSuperAdminGymsGymIdRoute
  '/dashboard/super-admin/gyms/add': typeof DashboardSuperAdminGymsAddRoute
  '/dashboard/admin/settings/': typeof DashboardAdminSettingsIndexRoute
  '/dashboard/super-admin/gyms/': typeof DashboardSuperAdminGymsIndexRoute
  '/dashboard/admin/plans/edit/$planId': typeof DashboardAdminPlansEditPlanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkin'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/dashboard/admin'
    | '/dashboard/m'
    | '/dashboard/super-admin'
    | '/api/public/auth-check'
    | '/dashboard/admin/account'
    | '/dashboard/admin/attendance'
    | '/dashboard/admin/members'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/plans'
    | '/dashboard/admin/qr-management'
    | '/dashboard/m/attendance'
    | '/dashboard/m/payments'
    | '/dashboard/m/plans'
    | '/dashboard/m/profile'
    | '/dashboard/super-admin/gyms'
    | '/dashboard/super-admin/payments'
    | '/dashboard/super-admin/plans'
    | '/dashboard/admin/'
    | '/dashboard/m/'
    | '/dashboard/super-admin/'
    | '/dashboard/admin/plans/new'
    | '/dashboard/super-admin/gyms/$gymId'
    | '/dashboard/super-admin/gyms/add'
    | '/dashboard/admin/settings/'
    | '/dashboard/super-admin/gyms/'
    | '/dashboard/admin/plans/edit/$planId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkin'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/api/public/auth-check'
    | '/dashboard/admin/account'
    | '/dashboard/admin/attendance'
    | '/dashboard/admin/members'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/plans'
    | '/dashboard/admin/qr-management'
    | '/dashboard/m/attendance'
    | '/dashboard/m/payments'
    | '/dashboard/m/plans'
    | '/dashboard/m/profile'
    | '/dashboard/super-admin/payments'
    | '/dashboard/super-admin/plans'
    | '/dashboard/admin'
    | '/dashboard/m'
    | '/dashboard/super-admin'
    | '/dashboard/admin/plans/new'
    | '/dashboard/super-admin/gyms/$gymId'
    | '/dashboard/super-admin/gyms/add'
    | '/dashboard/admin/settings'
    | '/dashboard/super-admin/gyms'
    | '/dashboard/admin/plans/edit/$planId'
  id:
    | '__root__'
    | '/'
    | '/checkin'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/dashboard/admin'
    | '/dashboard/m'
    | '/dashboard/super-admin'
    | '/api/public/auth-check'
    | '/dashboard/admin/account'
    | '/dashboard/admin/attendance'
    | '/dashboard/admin/members'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/plans'
    | '/dashboard/admin/qr-management'
    | '/dashboard/m/attendance'
    | '/dashboard/m/payments'
    | '/dashboard/m/plans'
    | '/dashboard/m/profile'
    | '/dashboard/super-admin/gyms'
    | '/dashboard/super-admin/payments'
    | '/dashboard/super-admin/plans'
    | '/dashboard/admin/'
    | '/dashboard/m/'
    | '/dashboard/super-admin/'
    | '/dashboard/admin/plans/new'
    | '/dashboard/super-admin/gyms/$gymId'
    | '/dashboard/super-admin/gyms/add'
    | '/dashboard/admin/settings/'
    | '/dashboard/super-admin/gyms/'
    | '/dashboard/admin/plans/edit/$planId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckinRoute: typeof CheckinRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  ApiPublicAuthCheckRoute: typeof ApiPublicAuthCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/m': {
      id: '/dashboard/m'
      path: '/m'
      fullPath: '/dashboard/m'
      preLoaderRoute: typeof DashboardMRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/super-admin': {
      id: '/dashboard/super-admin'
      path: '/super-admin'
      fullPath: '/dashboard/super-admin'
      preLoaderRoute: typeof DashboardSuperAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/auth-check': {
      id: '/api/public/auth-check'
      path: '/api/public/auth-check'
      fullPath: '/api/public/auth-check'
      preLoaderRoute: typeof ApiPublicAuthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/account': {
      id: '/dashboard/admin/account'
      path: '/account'
      fullPath: '/dashboard/admin/account'
      preLoaderRoute: typeof DashboardAdminAccountRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/attendance': {
      id: '/dashboard/admin/attendance'
      path: '/attendance'
      fullPath: '/dashboard/admin/attendance'
      preLoaderRoute: typeof DashboardAdminAttendanceRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/members': {
      id: '/dashboard/admin/members'
      path: '/members'
      fullPath: '/dashboard/admin/members'
      preLoaderRoute: typeof DashboardAdminMembersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/payments': {
      id: '/dashboard/admin/payments'
      path: '/payments'
      fullPath: '/dashboard/admin/payments'
      preLoaderRoute: typeof DashboardAdminPaymentsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/plans': {
      id: '/dashboard/admin/plans'
      path: '/plans'
      fullPath: '/dashboard/admin/plans'
      preLoaderRoute: typeof DashboardAdminPlansRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/qr-management': {
      id: '/dashboard/admin/qr-management'
      path: '/qr-management'
      fullPath: '/dashboard/admin/qr-management'
      preLoaderRoute: typeof DashboardAdminQrManagementRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/m/': {
      id: '/dashboard/m/'
      path: '/'
      fullPath: '/dashboard/m/'
      preLoaderRoute: typeof DashboardMIndexRouteImport
      parentRoute: typeof DashboardMRoute
    }
    '/dashboard/m/attendance': {
      id: '/dashboard/m/attendance'
      path: '/attendance'
      fullPath: '/dashboard/m/attendance'
      preLoaderRoute: typeof DashboardMAttendanceRouteImport
      parentRoute: typeof DashboardMRoute
    }
    '/dashboard/m/payments': {
      id: '/dashboard/m/payments'
      path: '/payments'
      fullPath: '/dashboard/m/payments'
      preLoaderRoute: typeof DashboardMPaymentsRouteImport
      parentRoute: typeof DashboardMRoute
    }
    '/dashboard/m/plans': {
      id: '/dashboard/m/plans'
      path: '/plans'
      fullPath: '/dashboard/m/plans'
      preLoaderRoute: typeof DashboardMPlansRouteImport
      parentRoute: typeof DashboardMRoute
    }
    '/dashboard/m/profile': {
      id: '/dashboard/m/profile'
      path: '/profile'
      fullPath: '/dashboard/m/profile'
      preLoaderRoute: typeof DashboardMProfileRouteImport
      parentRoute: typeof DashboardMRoute
    }
    '/dashboard/super-admin/': {
      id: '/dashboard/super-admin/'
      path: '/'
      fullPath: '/dashboard/super-admin/'
      preLoaderRoute: typeof DashboardSuperAdminIndexRouteImport
      parentRoute: typeof DashboardSuperAdminRoute
    }
    '/dashboard/super-admin/gyms': {
      id: '/dashboard/super-admin/gyms'
      path: '/gyms'
      fullPath: '/dashboard/super-admin/gyms'
      preLoaderRoute: typeof DashboardSuperAdminGymsRouteImport
      parentRoute: typeof DashboardSuperAdminRoute
    }
    '/dashboard/super-admin/payments': {
      id: '/dashboard/super-admin/payments'
      path: '/payments'
      fullPath: '/dashboard/super-admin/payments'
      preLoaderRoute: typeof DashboardSuperAdminPaymentsRouteImport
      parentRoute: typeof DashboardSuperAdminRoute
    }
    '/dashboard/super-admin/plans': {
      id: '/dashboard/super-admin/plans'
      path: '/plans'
      fullPath: '/dashboard/super-admin/plans'
      preLoaderRoute: typeof DashboardSuperAdminPlansRouteImport
      parentRoute: typeof DashboardSuperAdminRoute
    }
    '/dashboard/admin/plans/new': {
      id: '/dashboard/admin/plans/new'
      path: '/new'
      fullPath: '/dashboard/admin/plans/new'
      preLoaderRoute: typeof DashboardAdminPlansNewRouteImport
      parentRoute: typeof DashboardAdminPlansRoute
    }
    '/dashboard/admin/settings/': {
      id: '/dashboard/admin/settings/'
      path: '/settings'
      fullPath: '/dashboard/admin/settings/'
      preLoaderRoute: typeof DashboardAdminSettingsIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/super-admin/gyms/': {
      id: '/dashboard/super-admin/gyms/'
      path: '/'
      fullPath: '/dashboard/super-admin/gyms/'
      preLoaderRoute: typeof DashboardSuperAdminGymsIndexRouteImport
      parentRoute: typeof DashboardSuperAdminGymsRoute
    }
    '/dashboard/super-admin/gyms/$gymId': {
      id: '/dashboard/super-admin/gyms/$gymId'
      path: '/$gymId'
      fullPath: '/dashboard/super-admin/gyms/$gymId'
      preLoaderRoute: typeof DashboardSuperAdminGymsGymIdRouteImport
      parentRoute: typeof DashboardSuperAdminGymsRoute
    }
    '/dashboard/super-admin/gyms/add': {
      id: '/dashboard/super-admin/gyms/add'
      path: '/add'
      fullPath: '/dashboard/super-admin/gyms/add'
      preLoaderRoute: typeof DashboardSuperAdminGymsAddRouteImport
      parentRoute: typeof DashboardSuperAdminGymsRoute
    }
    '/dashboard/admin/plans/edit/$planId': {
      id: '/dashboard/admin/plans/edit/$planId'
      path: '/edit/$planId'
      fullPath: '/dashboard/admin/plans/edit/$planId'
      preLoaderRoute: typeof DashboardAdminPlansEditPlanIdRouteImport
      parentRoute: typeof DashboardAdminPlansRoute
    }
  }
}

interface DashboardAdminPlansRouteChildren {
  DashboardAdminPlansNewRoute: typeof DashboardAdminPlansNewRoute
  DashboardAdminPlansEditPlanIdRoute: typeof DashboardAdminPlansEditPlanIdRoute
}

const DashboardAdminPlansRouteChildren: DashboardAdminPlansRouteChildren = {
  DashboardAdminPlansNewRoute: DashboardAdminPlansNewRoute,
  DashboardAdminPlansEditPlanIdRoute: DashboardAdminPlansEditPlanIdRoute,
}

const DashboardAdminPlansRouteWithChildren =
  DashboardAdminPlansRoute._addFileChildren(DashboardAdminPlansRouteChildren)

interface DashboardAdminRouteChildren {
  DashboardAdminAccountRoute: typeof DashboardAdminAccountRoute
  DashboardAdminAttendanceRoute: typeof DashboardAdminAttendanceRoute
  DashboardAdminMembersRoute: typeof DashboardAdminMembersRoute
  DashboardAdminPaymentsRoute: typeof DashboardAdminPaymentsRoute
  DashboardAdminPlansRoute: typeof DashboardAdminPlansRouteWithChildren
  DashboardAdminQrManagementRoute: typeof DashboardAdminQrManagementRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardAdminSettingsIndexRoute: typeof DashboardAdminSettingsIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminAccountRoute: DashboardAdminAccountRoute,
  DashboardAdminAttendanceRoute: DashboardAdminAttendanceRoute,
  DashboardAdminMembersRoute: DashboardAdminMembersRoute,
  DashboardAdminPaymentsRoute: DashboardAdminPaymentsRoute,
  DashboardAdminPlansRoute: DashboardAdminPlansRouteWithChildren,
  DashboardAdminQrManagementRoute: DashboardAdminQrManagementRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardAdminSettingsIndexRoute: DashboardAdminSettingsIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardMRouteChildren {
  DashboardMAttendanceRoute: typeof DashboardMAttendanceRoute
  DashboardMPaymentsRoute: typeof DashboardMPaymentsRoute
  DashboardMPlansRoute: typeof DashboardMPlansRoute
  DashboardMProfileRoute: typeof DashboardMProfileRoute
  DashboardMIndexRoute: typeof DashboardMIndexRoute
}

const DashboardMRouteChildren: DashboardMRouteChildren = {
  DashboardMAttendanceRoute: DashboardMAttendanceRoute,
  DashboardMPaymentsRoute: DashboardMPaymentsRoute,
  DashboardMPlansRoute: DashboardMPlansRoute,
  DashboardMProfileRoute: DashboardMProfileRoute,
  DashboardMIndexRoute: DashboardMIndexRoute,
}

const DashboardMRouteWithChildren = DashboardMRoute._addFileChildren(
  DashboardMRouteChildren,
)

interface DashboardSuperAdminGymsRouteChildren {
  DashboardSuperAdminGymsGymIdRoute: typeof DashboardSuperAdminGymsGymIdRoute
  DashboardSuperAdminGymsAddRoute: typeof DashboardSuperAdminGymsAddRoute
  DashboardSuperAdminGymsIndexRoute: typeof DashboardSuperAdminGymsIndexRoute
}

const DashboardSuperAdminGymsRouteChildren: DashboardSuperAdminGymsRouteChildren =
  {
    DashboardSuperAdminGymsGymIdRoute: DashboardSuperAdminGymsGymIdRoute,
    DashboardSuperAdminGymsAddRoute: DashboardSuperAdminGymsAddRoute,
    DashboardSuperAdminGymsIndexRoute: DashboardSuperAdminGymsIndexRoute,
  }

const DashboardSuperAdminGymsRouteWithChildren =
  DashboardSuperAdminGymsRoute._addFileChildren(
    DashboardSuperAdminGymsRouteChildren,
  )

interface DashboardSuperAdminRouteChildren {
  DashboardSuperAdminGymsRoute: typeof DashboardSuperAdminGymsRouteWithChildren
  DashboardSuperAdminPaymentsRoute: typeof DashboardSuperAdminPaymentsRoute
  DashboardSuperAdminPlansRoute: typeof DashboardSuperAdminPlansRoute
  DashboardSuperAdminIndexRoute: typeof DashboardSuperAdminIndexRoute
}

const DashboardSuperAdminRouteChildren: DashboardSuperAdminRouteChildren = {
  DashboardSuperAdminGymsRoute: DashboardSuperAdminGymsRouteWithChildren,
  DashboardSuperAdminPaymentsRoute: DashboardSuperAdminPaymentsRoute,
  DashboardSuperAdminPlansRoute: DashboardSuperAdminPlansRoute,
  DashboardSuperAdminIndexRoute: DashboardSuperAdminIndexRoute,
}

const DashboardSuperAdminRouteWithChildren =
  DashboardSuperAdminRoute._addFileChildren(DashboardSuperAdminRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardMRoute: typeof DashboardMRouteWithChildren
  DashboardSuperAdminRoute: typeof DashboardSuperAdminRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardMRoute: DashboardMRouteWithChildren,
  DashboardSuperAdminRoute: DashboardSuperAdminRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckinRoute: CheckinRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  ApiPublicAuthCheckRoute: ApiPublicAuthCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
