/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardMRouteImport } from './routes/dashboard/m'
import { Route as DashboardSuperAdminRouteImport } from './routes/dashboard/super-admin'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as DashboardAdminAttendanceRouteImport } from './routes/dashboard/admin.attendance'
import { Route as DashboardAdminMembersRouteImport } from './routes/dashboard/admin.members'
import { Route as DashboardAdminPaymentsRouteImport } from './routes/dashboard/admin.payments'
import { Route as DashboardAdminPlansRouteImport } from './routes/dashboard/admin.plans'
import { Route as DashboardAdminSettingsRouteImport } from './routes/dashboard/admin.settings'
import { Route as DashboardMAttendanceRouteImport } from './routes/dashboard/m.attendance'
import { Route as DashboardMPaymentsRouteImport } from './routes/dashboard/m.payments'
import { Route as DashboardMProfileRouteImport } from './routes/dashboard/m.profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMRoute = DashboardMRouteImport.update({
  id: '/m',
  path: '/m',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSuperAdminRoute = DashboardSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminAttendanceRoute =
  DashboardAdminAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminMembersRoute = DashboardAdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminPaymentsRoute = DashboardAdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminPlansRoute = DashboardAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSettingsRoute = DashboardAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardMAttendanceRoute = DashboardMAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => DashboardMRoute,
} as any)
const DashboardMPaymentsRoute = DashboardMPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardMRoute,
} as any)
const DashboardMProfileRoute = DashboardMProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardMRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/m': typeof DashboardMRouteWithChildren
  '/dashboard/super-admin': typeof DashboardSuperAdminRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/attendance': typeof DashboardAdminAttendanceRoute
  '/dashboard/admin/members': typeof DashboardAdminMembersRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/admin/plans': typeof DashboardAdminPlansRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/m/attendance': typeof DashboardMAttendanceRoute
  '/dashboard/m/payments': typeof DashboardMPaymentsRoute
  '/dashboard/m/profile': typeof DashboardMProfileRoute
  '/auth/login/': typeof AuthLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/m': typeof DashboardMRouteWithChildren
  '/dashboard/super-admin': typeof DashboardSuperAdminRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/attendance': typeof DashboardAdminAttendanceRoute
  '/dashboard/admin/members': typeof DashboardAdminMembersRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/admin/plans': typeof DashboardAdminPlansRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/m/attendance': typeof DashboardMAttendanceRoute
  '/dashboard/m/payments': typeof DashboardMPaymentsRoute
  '/dashboard/m/profile': typeof DashboardMProfileRoute
  '/auth/login': typeof AuthLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/m': typeof DashboardMRouteWithChildren
  '/dashboard/super-admin': typeof DashboardSuperAdminRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/attendance': typeof DashboardAdminAttendanceRoute
  '/dashboard/admin/members': typeof DashboardAdminMembersRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/admin/plans': typeof DashboardAdminPlansRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/m/attendance': typeof DashboardMAttendanceRoute
  '/dashboard/m/payments': typeof DashboardMPaymentsRoute
  '/dashboard/m/profile': typeof DashboardMProfileRoute
  '/auth/login/': typeof AuthLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkin'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/m'
    | '/dashboard/super-admin'
    | '/dashboard/'
    | '/dashboard/admin/attendance'
    | '/dashboard/admin/members'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/plans'
    | '/dashboard/admin/settings'
    | '/dashboard/m/attendance'
    | '/dashboard/m/payments'
    | '/dashboard/m/profile'
    | '/auth/login/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkin'
    | '/dashboard/admin'
    | '/dashboard/m'
    | '/dashboard/super-admin'
    | '/dashboard'
    | '/dashboard/admin/attendance'
    | '/dashboard/admin/members'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/plans'
    | '/dashboard/admin/settings'
    | '/dashboard/m/attendance'
    | '/dashboard/m/payments'
    | '/dashboard/m/profile'
    | '/auth/login'
  id:
    | '__root__'
    | '/'
    | '/checkin'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/m'
    | '/dashboard/super-admin'
    | '/dashboard/'
    | '/dashboard/admin/attendance'
    | '/dashboard/admin/members'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/plans'
    | '/dashboard/admin/settings'
    | '/dashboard/m/attendance'
    | '/dashboard/m/payments'
    | '/dashboard/m/profile'
    | '/auth/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckinRoute: typeof CheckinRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/m': {
      id: '/dashboard/m'
      path: '/m'
      fullPath: '/dashboard/m'
      preLoaderRoute: typeof DashboardMRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/super-admin': {
      id: '/dashboard/super-admin'
      path: '/super-admin'
      fullPath: '/dashboard/super-admin'
      preLoaderRoute: typeof DashboardSuperAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/attendance': {
      id: '/dashboard/admin/attendance'
      path: '/attendance'
      fullPath: '/dashboard/admin/attendance'
      preLoaderRoute: typeof DashboardAdminAttendanceRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/members': {
      id: '/dashboard/admin/members'
      path: '/members'
      fullPath: '/dashboard/admin/members'
      preLoaderRoute: typeof DashboardAdminMembersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/payments': {
      id: '/dashboard/admin/payments'
      path: '/payments'
      fullPath: '/dashboard/admin/payments'
      preLoaderRoute: typeof DashboardAdminPaymentsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/plans': {
      id: '/dashboard/admin/plans'
      path: '/plans'
      fullPath: '/dashboard/admin/plans'
      preLoaderRoute: typeof DashboardAdminPlansRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/settings': {
      id: '/dashboard/admin/settings'
      path: '/settings'
      fullPath: '/dashboard/admin/settings'
      preLoaderRoute: typeof DashboardAdminSettingsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/m/attendance': {
      id: '/dashboard/m/attendance'
      path: '/attendance'
      fullPath: '/dashboard/m/attendance'
      preLoaderRoute: typeof DashboardMAttendanceRouteImport
      parentRoute: typeof DashboardMRoute
    }
    '/dashboard/m/payments': {
      id: '/dashboard/m/payments'
      path: '/payments'
      fullPath: '/dashboard/m/payments'
      preLoaderRoute: typeof DashboardMPaymentsRouteImport
      parentRoute: typeof DashboardMRoute
    }
    '/dashboard/m/profile': {
      id: '/dashboard/m/profile'
      path: '/profile'
      fullPath: '/dashboard/m/profile'
      preLoaderRoute: typeof DashboardMProfileRouteImport
      parentRoute: typeof DashboardMRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminAttendanceRoute: typeof DashboardAdminAttendanceRoute
  DashboardAdminMembersRoute: typeof DashboardAdminMembersRoute
  DashboardAdminPaymentsRoute: typeof DashboardAdminPaymentsRoute
  DashboardAdminPlansRoute: typeof DashboardAdminPlansRoute
  DashboardAdminSettingsRoute: typeof DashboardAdminSettingsRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminAttendanceRoute: DashboardAdminAttendanceRoute,
  DashboardAdminMembersRoute: DashboardAdminMembersRoute,
  DashboardAdminPaymentsRoute: DashboardAdminPaymentsRoute,
  DashboardAdminPlansRoute: DashboardAdminPlansRoute,
  DashboardAdminSettingsRoute: DashboardAdminSettingsRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardMRouteChildren {
  DashboardMAttendanceRoute: typeof DashboardMAttendanceRoute
  DashboardMPaymentsRoute: typeof DashboardMPaymentsRoute
  DashboardMProfileRoute: typeof DashboardMProfileRoute
}

const DashboardMRouteChildren: DashboardMRouteChildren = {
  DashboardMAttendanceRoute: DashboardMAttendanceRoute,
  DashboardMPaymentsRoute: DashboardMPaymentsRoute,
  DashboardMProfileRoute: DashboardMProfileRoute,
}

const DashboardMRouteWithChildren = DashboardMRoute._addFileChildren(
  DashboardMRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardMRoute: typeof DashboardMRouteWithChildren
  DashboardSuperAdminRoute: typeof DashboardSuperAdminRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardMRoute: DashboardMRouteWithChildren,
  DashboardSuperAdminRoute: DashboardSuperAdminRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckinRoute: CheckinRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
